version: '3.3'

services:
  redis:
    image: redis:latest
    ports:
      - 6379:6379

  redis-worker:
    build:
      context: .
      dockerfile: dockerfiles/redis-worker.dockerfile
    command: rq worker --url redis://redis:6379
    depends_on:
      - redis
    links:
      - redis

  monogo-db:
    image: mongo:latest
    ports:
      - 27017:27017
